version: "3.9"

services:
  mongo1:
    networks:
      - default
      - mongo-network
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0",  "--port", "27017", ]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    ports:
      - "27018:27018"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27018" ]
    volumes:
      - mongo2_data:/data/db

  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo
    ports:
      - "27019:27019"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27019" ]
    volumes:
      - mongo3_data:/data/db

  mongo_setup:
    container_name: mongo_setup
    image: mongo
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    ports:
      - "8081:8081"
    environment:
      #      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMIN_USERNAME}
      #      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo1:27017,mongo2:27018,mongo3:27019/rs0?replicaSet=rs0

networks:
  mongo-network:
    driver: bridge


volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: